Improve credential how-to description in README
fsspec/adlfs pull request #367
Opened 2022-11-16 13:09 UTC by PeterFogh

I have used adlfs the last year using `account_key` but found out today that Azure automatically can find available credentials when using `storage_options={'account_name': ACCOUNT_NAME, 'anon': False}`. I thought this could be documented more clearly, thus I like to add these changes to the docs.

Thanks to @charles-mccall for helping me.

2022-11-17 14:28 UTC, efiop commented on README.md
> +The filesystem can be instantiated for different use cases base on a variety of `storage_options` combinations. The following list describes some commen use cases utilizing `AzureBlobFileSystem`, i.e
```suggestion
The filesystem can be instantiated for different use cases based on a variety of `storage_options` combinations. The following list describes some common use cases utilizing `AzureBlobFileSystem`, i.e. protocols `abfs`or `az`. Note that all cases require the `account_name` argument to be provided:
```

2022-11-17 14:29 UTC, efiop commented on README.md
> -
Unrelated change.

2022-11-17 14:30 UTC, efiop commented on README.md
> +3. Azure ServicePrincipal: `tenant_id`, `client_id`, and `client_secret` are all used as crendentials for a Azure ServicePrincipal: e.g. `storage_options={'account_name': ACCOUNT_NAME, 'tenant_id': T
```suggestion
3. Azure ServicePrincipal: `tenant_id`, `client_id`, and `client_secret` are all used as credentials for an Azure ServicePrincipal: e.g. `storage_options={'account_name': ACCOUNT_NAME, 'tenant_id': TENANT_ID, 'client_id': CLIENT_ID, 'client_secret': CLIENT_SECRET}`.
```

2022-11-17 14:33 UTC, efiop requested changes
Some minor typos, but looks great to me overall.

@PeterFogh Long time no see ;) Hope you are doing great.

2022-11-23 01:15 UTC, hayesgb commented
LGTM!  Thanks @PeterFogh !

2022-11-23 01:16 UTC, merged